services:
  rethinkdb:
    image: rethinkdb:latest
    container_name: rethinkdb-order-drink
    volumes:
      - ./rethinkdb-data:/data
    ports:
      - "9000:8080"
      - "28015:28015"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
      interval: 5s
      retries: 20
      start_period: 5s

  app:
    build: .
    image: gray9527/order-drink-app:latest # 若本地測試可註解掉
    container_name: order-drink-app
    restart: unless-stopped
    environment:
      - REACT_APP_TITLE=${REACT_APP_TITLE}
      - REACT_APP_STORE_NAME=${REACT_APP_STORE_NAME}
      - REACT_APP_DISABLED_MENU=${REACT_APP_DISABLED_MENU}
      - REACT_APP_ADMIN_PASSWORD=${REACT_APP_ADMIN_PASSWORD}
      - RETHINKDB_HOST=rethinkdb
    ports:
      - "5918:5918"
    depends_on:
      rethinkdb:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O- http://localhost:5918 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
